---
- hosts: elk
  become: yes
  gather_facts: no
  roles:
    - elastic_stack
  tasks:
    - name: ensure elasticsearch installed
      apt:
        name: elasticsearch
        state: present

    - name: Change Elasticsearch's initial heap size.
      lineinfile:
        dest: /etc/elasticsearch/jvm.options
        regexp: '^-Xms.+$'
        line: '-Xms2g'
        state: present

    - name: Change Elasticsearch's max heap size.
      lineinfile:
        dest: /etc/elasticsearch/jvm.options
        regexp: '^-Xmx.+$'
        line: '-Xmx2g'
        state: present

    - name: ensure config uploaded
      copy:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
