---
- hosts: elk
  become: yes
  gather_facts: no
  roles:
    - elastic_stack
  tasks:
    - name: ensure kibana installed
      apt:
        name: kibana
        state: present

    - name: ensure kibana is started
      service:
        name: kibana
        state: started
        enabled: true